name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libtool intltool autopoint libasound2-dev libpulse-dev libjack-jackd2-dev libfftw3-dev libgtk-3-dev libcunit1-dev libjson-c-dev
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: cat test log
      run: cat ./test-suite.log
    - name: make distcheck
      run: make distcheck
    - name: configure no fftw
      run: ./configure --with-fftw=no
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
